# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=30)),
                ('current_stage', models.IntegerField(default=0)),
                ('checklist_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('project_date', models.DateTimeField(verbose_name='date published')),
                ('project_stage_max', models.IntegerField(default=0)),
                ('project_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='checklistdata',
            name='projectdata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.ProjectData'),
        ),
    ]
